
package com.servicio.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "empleadoPortService", targetNamespace = "http://www.servicio.com/empleado-ws", wsdlLocation = "file:/D:/src/empleados.wsdl")
public class EmpleadoPortService
    extends Service
{

    private final static URL EMPLEADOPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException EMPLEADOPORTSERVICE_EXCEPTION;
    private final static QName EMPLEADOPORTSERVICE_QNAME = new QName("http://www.servicio.com/empleado-ws", "empleadoPortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/src/empleados.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EMPLEADOPORTSERVICE_WSDL_LOCATION = url;
        EMPLEADOPORTSERVICE_EXCEPTION = e;
    }

    public EmpleadoPortService() {
        super(__getWsdlLocation(), EMPLEADOPORTSERVICE_QNAME);
    }

    public EmpleadoPortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EMPLEADOPORTSERVICE_QNAME, features);
    }

    public EmpleadoPortService(URL wsdlLocation) {
        super(wsdlLocation, EMPLEADOPORTSERVICE_QNAME);
    }

    public EmpleadoPortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EMPLEADOPORTSERVICE_QNAME, features);
    }

    public EmpleadoPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmpleadoPortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EmpleadoPort
     */
    @WebEndpoint(name = "empleadoPortSoap11")
    public EmpleadoPort getEmpleadoPortSoap11() {
        return super.getPort(new QName("http://www.servicio.com/empleado-ws", "empleadoPortSoap11"), EmpleadoPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmpleadoPort
     */
    @WebEndpoint(name = "empleadoPortSoap11")
    public EmpleadoPort getEmpleadoPortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.servicio.com/empleado-ws", "empleadoPortSoap11"), EmpleadoPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EMPLEADOPORTSERVICE_EXCEPTION!= null) {
            throw EMPLEADOPORTSERVICE_EXCEPTION;
        }
        return EMPLEADOPORTSERVICE_WSDL_LOCATION;
    }

}
