package com.servicio.empleado.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmpleadosPort", targetNamespace = "http://www.servicio.com/empleado-ws")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ ObjectFactory.class })
public interface EmpleadosPort {

	/**
	 * 
	 * @param addEmpleadoRequest
	 * @return returns com.servicio.empleado_ws.AddEmpleadoResponse
	 */
	@WebMethod
	@WebResult(name = "addEmpleadoResponse", targetNamespace = "http://www.servicio.com/empleado-ws", partName = "addEmpleadoResponse")
	public AddEmpleadoResponse addEmpleado(
			@WebParam(name = "addEmpleadoRequest", targetNamespace = "http://www.servicio.com/empleado-ws", partName = "addEmpleadoRequest") AddEmpleadoRequest addEmpleadoRequest);

}
